### ISSUE TITLE
we need some additional type or class

### ISSUE THREAD

**Issue by 97e57e** [payw-org/eodiro-server#48]
## AuthOptional type
- There ara api's they need auth optional

## modelRepository
- database access object

**Comment by 97e57e** [comment]
### about repository pattern

- https://medium.com/@erickwendel/generic-repository-with-typescript-and-node-js-731c10a1b98e

**Comment by jhaemin** [comment]
https://github.com/payw-org/eodiro-server/releases/tag/v2.2.0-beta.1
